name: Build packages

on:
  push:
    branches: [ "master" ]
    paths: [ 'XoW.sln', 'XoW/**', '.github/workflows/build.yml' ]
  workflow_dispatch:

jobs:
  build:
    name: Build packages
    runs-on: windows-latest
    env:
      APP_PACKAGES_DIRECTORY: $pwd\AppPackages
    steps:
      - uses: actions/checkout@v3
          
      - name: Cache nuget packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install signing certificate
        shell: pwsh
        env:
          PFX_CONTENT: ${{ secrets.SIGNING_CERTIFICATE }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
        run: |
          echo "Saving the certificate to $($env:RUNNER_TEMP)";
          $pfxPath = Join-Path -Path $env:RUNNER_TEMP -ChildPath "cert.pfx";
          $encodedBytes = [System.Convert]::FromBase64String($env:PFX_CONTENT);
          Set-Content $pfxPath -Value $encodedBytes -AsByteStream;
          echo "Installing certificate from $($env:RUNNER_TEMP)\cert.pfx";
          Import-PfxCertificate -FilePath "$($env:RUNNER_TEMP)\cert.pfx" -CertStoreLocation Cert:\CurrentUser\My -Password (ConvertTo-SecureString -String $env:SIGNING_CERTIFICATE_PASSWORD -Force -AsPlainText);

      - name: Add AppConfig.xml to working directory
        shell: pwsh
        env:
          APP_CONFIG_XML: ${{ secrets.APP_CONFIG_XML }}
        run: |
          echo "Adding AppConfig.xml to $($env:GITHUB_WORKSPACE)\XoW";
          $filePath = Join-Path -Path "$($env:GITHUB_WORKSPACE)\XoW" -ChildPath "AppConfig.xml";
          $encodedBytes = [System.Convert]::FromBase64String($env:APP_CONFIG_XML);
          Set-Content $filePath -Value $encodedBytes -AsByteStream;

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build packages
        shell: pwsh
        run: >-
          msbuild
          "XoW.sln"
          /restore
          /m
          /verbosity:minimal
          /target:Rebuild
          /nodeReuse:false
          /p:RestoreLockedMode=true
          /p:AppxBundle=Always
          /p:AppxPackageDir="${{ env.APP_PACKAGES_DIRECTORY }}"
          /p:UapAppxPackageBuildMode=StoreAndSideload
          /p:AppxBundlePlatforms="x86|x64|ARM|ARM64"
          /p:configuration="Release"
          /p:VisualStudioVersion="17.0"
      
      - name: Load package version
        shell: pwsh
        run: |
          [xml]$manifest = Get-Content "$pwd\XoW\Package.appxmanifest"
          echo "VERSION=$manifest.Package.Identity.Version" >> $env:GITHUB_ENV
      
      - shell: pwsh
        run: tree ${{ env.APP_PACKAGES_DIRECTORY }} /f

      - name: Upload workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: |
            ${{ env.APP_PACKAGES_DIRECTORY }}\XoW_${{ env.VERSION }}_Test\XoW_${{ env.VERSION }}_x86_x64_arm_arm64.msixbundle
            ${{ env.APP_PACKAGES_DIRECTORY }}\XoW_${{ env.VERSION }}_x86_x64_arm_arm64_bundle.msixupload
